### ISSUE TITLE
CVE-2020-15228 - Contains usage of now deprecated `add-path`

### ISSUE THREAD

**Issue by DoctorMcKay** [warrenbuckley/Setup-Nuget#11]
Related CVE - [GHSA-mfwh-5m23-j46w](https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w)

Output from Github Actions:

```
Run warrenbuckley/Setup-Nuget@v1
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

Related: microsoft/setup-msbuild#26

**Comment by yellowberryHN** [comment]
As the deadline is now hard set to November 16th, It'd be a good time to make the fix.

**Comment by mizar** [comment]
@actions/core 1.2.6 includes a fix for this issue. Bumping https://github.com/warrenbuckley/Setup-Nuget/pull/10 and rebuilding this may solve the problem.

Related: https://github.com/nttld/setup-ndk/pull/30

**Comment by mizar** [comment]
a stopgap example:

```
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: warrenbuckley/Setup-Nuget
        path: setup-nuget
    - run: |
        sed -i 's(\"@actions/core\": \"\^1.0.0\"(\"@actions/core\": \"^1.2.6\"(' package.json
        cat package.json
        npm install
        npm build
      working-directory: setup-nuget
    - uses: ./setup-nuget
    #- uses: warrenbuckley/Setup-Nuget@v1
```
