### ISSUE TITLE
how do myget.org to the package source

### ISSUE THREAD

**Issue by MohMehrnia** [warrenbuckley/Setup-Nuget#5]
how do acc myget.org to the package source?
I Used below syntax but not work:
```
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
    - name: Setup NuGet Sources
      run: nuget sources add -name "MyGet" -Source "https://www.myget.org/F/my/api/v3/index.json"
    - name: dotnet Restore
      run: dotnet restore
    - name: Build with dotnet
      run: dotnet build ./TurbineJobMVC.sln --configuration Release

```
